services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: monserratesabe-db
    hostname: monserratesabe-db
    image: postgres:17.3
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-monserratesabe}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-monserratesabe}
      POSTGRES_DB: ${POSTGRES_DB:-monserratesabe}

volumes:
  postgres:
    driver: local
