services:
  db:
    image: postgres:17-alpine
    container_name: monserratesabe-db
    hostname: monserratesabe-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: monserratesabe
      POSTGRES_PASSWORD: monserratesabe
      POSTGRES_DB: monserratesabe